# Generated by Django 5.2.6 on 2025-10-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Токен авторизации"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Электронная почта"
            ),
        ),
    ]
