# Generated by Django 5.2.6 on 2025-10-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blognote",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Метка публикации"),
        ),
    ]
