# Generated by Django 5.2.6 on 2025-10-25 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blognote_is_published"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blognote",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_unpublish_blog_note", "Can unpublish Blog note")],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.AddField(
            model_name="blognote",
            name="owner",
            field=models.ForeignKey(
                default=14,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
            preserve_default=False,
        ),
    ]
