# Generated by Django 5.2.6 on 2025-10-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contacts_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Наименование"
            ),
        ),
    ]
